logic [31:0] pc;
assign pc = sc_soc_tb.u_dut.u_core.core_i.id_stage_i.pc_id_i[31:0];

// regfile internal probing
`define REGFILE_SEE(__NAME__,__INDEX__,__TYPE__,__EXT__)                                         \
  logic [31:0] ``__TYPE__``_``__INDEX__``_``__NAME__``;                                          \
  assign ``__TYPE__``_``__INDEX__``_``__NAME__`` =                                               \
  sc_soc_tb.u_dut.u_core.core_i.id_stage_i.register_file_i.``__EXT__``[``__INDEX__``];           \


`REGFILE_SEE(zero,0,x,mem)
`REGFILE_SEE(ra,1,x,mem)
`REGFILE_SEE(sp,2,x,mem)
`REGFILE_SEE(gp,3,x,mem)
`REGFILE_SEE(tp,4,x,mem)
`REGFILE_SEE(t0,5,x,mem)
`REGFILE_SEE(t1,6,x,mem)
`REGFILE_SEE(t2,7,x,mem)
`REGFILE_SEE(s0_fp,8,x,mem)
`REGFILE_SEE(s1,9,x,mem)
`REGFILE_SEE(a0,10,x,mem)
`REGFILE_SEE(a1,11,x,mem)
`REGFILE_SEE(a2,12,x,mem)
`REGFILE_SEE(a3,13,x,mem)
`REGFILE_SEE(a4,14,x,mem)
`REGFILE_SEE(a5,15,x,mem)
`REGFILE_SEE(a6,16,x,mem)
`REGFILE_SEE(a7,17,x,mem)
`REGFILE_SEE(s2,18,x,mem)
`REGFILE_SEE(s3,19,x,mem)
`REGFILE_SEE(s4,20,x,mem)
`REGFILE_SEE(s5,21,x,mem)
`REGFILE_SEE(s6,22,x,mem)
`REGFILE_SEE(s7,23,x,mem)
`REGFILE_SEE(s8,24,x,mem)
`REGFILE_SEE(s9,25,x,mem)
`REGFILE_SEE(s10,26,x,mem)
`REGFILE_SEE(s11,27,x,mem)
`REGFILE_SEE(t3,28,x,mem)
`REGFILE_SEE(t4,29,x,mem)
`REGFILE_SEE(t5,30,x,mem)
`REGFILE_SEE(t6,31,x,mem)

`REGFILE_SEE(ft0,0,f,mem_fp)
`REGFILE_SEE(ft1,1,f,mem_fp)
`REGFILE_SEE(ft2,2,f,mem_fp)
`REGFILE_SEE(ft3,3,f,mem_fp)
`REGFILE_SEE(ft4,4,f,mem_fp)
`REGFILE_SEE(ft5,5,f,mem_fp)
`REGFILE_SEE(ft6,6,f,mem_fp)
`REGFILE_SEE(ft7,7,f,mem_fp)
`REGFILE_SEE(fs0,8,f,mem_fp)
`REGFILE_SEE(fs1,9,f,mem_fp)
`REGFILE_SEE(fa0,10,f,mem_fp)
`REGFILE_SEE(fa1,11,f,mem_fp)
`REGFILE_SEE(fa2,12,f,mem_fp)
`REGFILE_SEE(fa3,13,f,mem_fp)
`REGFILE_SEE(fa4,14,f,mem_fp)
`REGFILE_SEE(fa5,15,f,mem_fp)
`REGFILE_SEE(fa6,16,f,mem_fp)
`REGFILE_SEE(fa7,17,f,mem_fp)
`REGFILE_SEE(fs2,18,f,mem_fp)
`REGFILE_SEE(fs3,19,f,mem_fp)
`REGFILE_SEE(fs4,20,f,mem_fp)
`REGFILE_SEE(fs5,21,f,mem_fp)
`REGFILE_SEE(fs6,22,f,mem_fp)
`REGFILE_SEE(fs7,23,f,mem_fp)
`REGFILE_SEE(fs8,24,f,mem_fp)
`REGFILE_SEE(fs9,25,f,mem_fp)
`REGFILE_SEE(fs10,26,f,mem_fp)
`REGFILE_SEE(fs11,27,f,mem_fp)
`REGFILE_SEE(t8,28,f,mem_fp)
`REGFILE_SEE(t9,29,f,mem_fp)
`REGFILE_SEE(t10,30,f,mem_fp)
`REGFILE_SEE(t11,31,f,mem_fp)

`undef REGFILE_SEE
